---
- name: Audit | Enabling the service on boot 
  service:
    name: auditd
    state: started
    enabled: yes
  tags: ['audit', 'm3_@@5']

- name:  Audit | Configuring auditd.conf
  template: 
      src=auditd.conf.j2
      dest=/etc/audit/auditd.conf
      backup=yes
  tags: ['audit', 'm3_@@5']

- name: Audit | Generate audit.d/audit.rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    mode: 0640
  tags: ['audit', 'm3_@@5']

